# Generated by Django 5.2.14 on 2026-05-30 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('SUPREME', 'Supreme Court'), ('APPEALS', 'Court of Appeals')], max_length=16)),
                ('name', models.CharField(help_text="Display name, e.g. 'Minnesota Supreme Court'.", max_length=128)),
                ('slug', models.SlugField(max_length=64)),
                ('courtlistener_id', models.CharField(help_text="CourtListener court identifier (e.g. 'minn', 'minnctapp').", max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['state__code', 'level'],
            },
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RETIRED', 'Retired'), ('SENIOR', 'Senior'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=16)),
                ('courtlistener_id', models.CharField(blank=True, default='', help_text='CourtListener person identifier, when known.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('code', models.CharField(help_text="USPS 2-letter code, uppercase. e.g. 'MN'.", max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(help_text='Lowercase subdomain slug; matches code.', max_length=64, unique=True)),
                ('is_live', models.BooleanField(default=False, help_text="True once this state's subdomain is advertised on the apex picker.")),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(help_text="Docket number as published, e.g. 'A23-0123'.", max_length=64)),
                ('title', models.TextField(help_text='Case caption / title.')),
                ('release_date', models.DateField(db_index=True)),
                ('is_precedential', models.BooleanField(default=True)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('html_content', models.TextField(blank=True, default='')),
                ('source_url', models.URLField(blank=True, default='', max_length=512)),
                ('courtlistener_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('sha256', models.CharField(blank=True, default='', help_text='Hash of the raw text, for dedupe.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opinions', to='opinions.court')),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='OpinionHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statute_cited', models.CharField(blank=True, db_index=True, default='', help_text="Normalized statute reference, e.g. 'Minn. Stat. 609.185'.", max_length=128)),
                ('legal_issue_tag', models.CharField(blank=True, default='', help_text='Free-form tag for the legal issue addressed.', max_length=128)),
                ('holding_direction', models.CharField(choices=[('AFFIRMED', 'Affirmed'), ('REVERSED', 'Reversed'), ('REMANDED', 'Remanded'), ('VACATED', 'Vacated'), ('SUPPRESSED', 'Suppressed'), ('ADMITTED', 'Admitted'), ('GRANTED', 'Granted'), ('DENIED', 'Denied'), ('OTHER', 'Other')], default='OTHER', max_length=16)),
                ('holding_text', models.TextField()),
                ('embedding', models.JSONField(blank=True, help_text='Sentence embedding for similarity search; null until generated. Migrate to MariaDB VECTOR column for indexed lookups in prod.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='opinions.opinion')),
            ],
            options={
                'ordering': ['opinion', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PanelVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('MAJORITY_AUTHOR', 'Majority author'), ('MAJORITY_JOIN', 'Joined majority'), ('CONCURRENCE_AUTHOR', 'Concurrence author'), ('CONCURRENCE_JOIN', 'Joined concurrence'), ('DISSENT_AUTHOR', 'Dissent author'), ('DISSENT_JOIN', 'Joined dissent'), ('RECUSED', 'Recused'), ('NOT_PARTICIPATING', 'Did not participate')], max_length=24)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='panel_votes', to='opinions.judge')),
                ('opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_votes', to='opinions.opinion')),
            ],
        ),
        migrations.AddField(
            model_name='judge',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='judges', to='opinions.state'),
        ),
        migrations.AddField(
            model_name='court',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courts', to='opinions.state'),
        ),
        migrations.AddIndex(
            model_name='opinion',
            index=models.Index(fields=['-release_date'], name='opinions_op_release_a6fcc9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='opinion',
            unique_together={('court', 'case_number')},
        ),
        migrations.AddIndex(
            model_name='panelvote',
            index=models.Index(fields=['judge', 'vote_type'], name='opinions_pa_judge_i_1195d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='panelvote',
            unique_together={('opinion', 'judge')},
        ),
        migrations.AlterUniqueTogether(
            name='judge',
            unique_together={('state', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='court',
            unique_together={('state', 'level')},
        ),
    ]
