# Generated by Django 5.2.14 on 2026-06-03 17:49

import opinions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0003_seed_mn_courts'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='pdf_file',
            field=models.FileField(blank=True, help_text="Optional uploaded PDF. If provided and raw_text is empty, the text is extracted on save (via pypdf) and the sha256 computed. Re-uploading without clearing raw_text won't re-extract.", null=True, upload_to=opinions.models._opinion_pdf_upload_path),
        ),
    ]
