# Generated by Django 5.2.14 on 2026-06-04 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0004_opinion_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='disposition',
            field=models.CharField(blank=True, default='', help_text="Overall result for the case (e.g. 'Affirmed', 'Reversed and remanded'). Separate from per-holding direction on OpinionHolding.", max_length=128),
        ),
        migrations.CreateModel(
            name='ParseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parser_state', models.CharField(help_text="State code (e.g. 'MN') of the parser that ran.", max_length=2)),
                ('parser_version', models.CharField(default='v1', help_text='Bumped when parser rules change in a way that affects output.', max_length=16)),
                ('extracted', models.JSONField(default=dict, help_text='The full ParsedOpinion serialized as JSON (release_date is ISO).')),
                ('missing_fields', models.JSONField(default=list, help_text="Tracked top-level fields the parser couldn't fill in.")),
                ('raw_text_sha256', models.CharField(help_text='SHA-256 of raw_text at parse time. Used to skip re-parses of unchanged text.', max_length=64)),
                ('duration_ms', models.IntegerField(default=0, help_text='Wall-clock parse time in milliseconds.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parse_logs', to='opinions.opinion')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['parser_state', '-created_at'], name='opinions_pa_parser__858d11_idx'), models.Index(fields=['opinion', '-created_at'], name='opinions_pa_opinion_399021_idx')],
            },
        ),
    ]
