# Generated by Django 5.2.14 on 2026-06-04 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0006_normalize_existing_docket_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='appointment_date',
            field=models.DateField(blank=True, help_text='When this judge took the bench in their current role.', null=True),
        ),
        migrations.AddField(
            model_name='judge',
            name='bio_summary',
            field=models.TextField(blank=True, default='', help_text='Short paragraph from the official bio. Plain text, no HTML.'),
        ),
        migrations.AddField(
            model_name='judge',
            name='bio_url',
            field=models.URLField(blank=True, default='', help_text="Link to the judge's official bio page (e.g. mncourts.gov/judges/...).", max_length=512),
        ),
        migrations.AddField(
            model_name='judge',
            name='court',
            field=models.ForeignKey(blank=True, help_text='Primary court this judge sits on. Null for historical or unmapped rows.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='judges', to='opinions.court'),
        ),
        migrations.AddField(
            model_name='judge',
            name='is_currently_seated',
            field=models.BooleanField(default=False, help_text='True if this judge appears on the current judicial roster.'),
        ),
        migrations.AddField(
            model_name='judge',
            name='photo_url',
            field=models.URLField(blank=True, default='', help_text='External URL of the official portrait. Self-hosted later.', max_length=512),
        ),
        migrations.AddField(
            model_name='judge',
            name='role',
            field=models.CharField(blank=True, choices=[('CHIEF_JUSTICE', 'Chief Justice'), ('ASSOCIATE_JUSTICE', 'Associate Justice'), ('CHIEF_JUDGE', 'Chief Judge'), ('JUDGE', 'Judge'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=24),
        ),
        migrations.AddField(
            model_name='judge',
            name='source_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Stable ID from the source roster (e.g. mncourts.gov slug). For scraper idempotency.', max_length=128),
        ),
        migrations.AlterField(
            model_name='judge',
            name='courtlistener_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='CourtListener person identifier, when known.', max_length=64),
        ),
        migrations.AlterField(
            model_name='judge',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SENIOR', 'Senior'), ('RETIRED', 'Retired'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=16),
        ),
        migrations.AddIndex(
            model_name='judge',
            index=models.Index(fields=['state', 'is_currently_seated'], name='opinions_ju_state_i_6808f3_idx'),
        ),
        migrations.AddIndex(
            model_name='judge',
            index=models.Index(fields=['court', 'is_currently_seated'], name='opinions_ju_court_i_44e989_idx'),
        ),
    ]
