# Generated by Django 5.2.14 on 2026-06-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0007_judge_appointment_date_judge_bio_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='disposition_bucket',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Auto-populated outcome bucket slug (affirmed / reversed / vacated / ...). Indexed for fast filtering from the sidebar Outcomes legend.', max_length=24),
        ),
    ]
