# Generated by Django 5.2.14 on 2026-06-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0009_backfill_disposition_buckets'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='review_notes',
            field=models.TextField(blank=True, default='', help_text='Internal editor notes. Not shown publicly.'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='review_status',
            field=models.CharField(choices=[('ai_only', 'AI-processed only'), ('flagged', 'Flagged for review'), ('reviewed', 'Human-reviewed')], db_index=True, default='ai_only', help_text='Editorial review state. Shown publicly so readers know whether a human has read and curated this opinion vs. whether it has only been machine-processed. Default for ingested opinions is AI-processed; flip via admin action when reviewed.', max_length=16),
        ),
        migrations.AddField(
            model_name='opinion',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='Auto-stamped when review_status flips to human-reviewed.', null=True),
        ),
        migrations.AddField(
            model_name='opinion',
            name='reviewed_by',
            field=models.CharField(blank=True, default='', help_text='Username of the editor who marked this opinion human-reviewed.', max_length=120),
        ),
    ]
