# Generated by Django 5.2.14 on 2026-06-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0013_opinion_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(help_text="What the user typed -- could be 'California', 'CA', 'Puerto Rico'.", max_length=64)),
                ('email', models.EmailField(blank=True, default='', help_text="Optional. If provided, we'll email when their state goes live.", max_length=254)),
                ('notes', models.TextField(blank=True, default='', help_text='Optional. Anything the requester wants to tell us.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='For anti-spam triage. Admin-only; never shown publicly.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['state_name'], name='opinions_st_state_n_4f13c6_idx'), models.Index(fields=['-created_at'], name='opinions_st_created_dacd7e_idx')],
            },
        ),
    ]
