# Generated by Django 5.2.14 on 2026-06-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0015_opinion_vector_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryEmbedding',
            fields=[
                ('query', models.CharField(help_text='Lowercase-normalized search query.', max_length=512, primary_key=True, serialize=False)),
                ('embedding_json', models.TextField(help_text='JSON array of 1024 floats -- the Voyage embedding for ``query``.')),
                ('hit_count', models.PositiveIntegerField(default=1, help_text='How many times this cached embedding has been served.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Used for LRU eviction if the cache ever needs trimming.')),
            ],
            options={
                'ordering': ['-last_used_at'],
            },
        ),
    ]
