# Generated by Django 5.2.14 on 2026-06-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0016_add_query_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryembedding',
            name='query',
            field=models.CharField(help_text="Lowercase-normalized search query. Capped at 255 so the column fits within MariaDB's unique-index key size on utf8mb4. Longer queries bypass the cache via the semantic.QUERY_LENGTH_CAP check.", max_length=255, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('slug', models.SlugField(help_text="URL-safe identifier; used in /tag/<slug>/. Stable; don't change.", max_length=64, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='Display name shown in chips, browse pages, admin lists.', max_length=100)),
                ('category', models.CharField(choices=[('doctrine', 'Doctrine'), ('subject', 'Subject matter'), ('procedural', 'Procedural'), ('posture', 'Posture / significance')], db_index=True, default='doctrine', help_text='Groups tags on the browse page; mental scaffolding for the editor.', max_length=24)),
                ('description', models.TextField(blank=True, default='', help_text='Brief explanation of what this tag covers. Shown on browse pages.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'label'],
                'indexes': [models.Index(fields=['category', 'label'], name='opinions_ta_categor_4571d7_idx')],
            },
        ),
        migrations.AddField(
            model_name='opinion',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Editorial tags applied to this opinion. Public; see Tag model.', related_name='opinions', to='opinions.tag'),
        ),
    ]
