# Generated by Django 5.2.14 on 2026-06-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0018_seed_starter_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='review_status',
            field=models.CharField(choices=[('ai_only', 'Processed'), ('flagged', 'Flagged for review'), ('reviewed', 'Human-reviewed')], db_index=True, default='ai_only', help_text='Editorial review state. Shown publicly so readers know whether a human has read and curated this opinion vs. whether it has only been machine-processed. Default for ingested opinions is AI-processed; flip via admin action when reviewed.', max_length=16),
        ),
    ]
