# Generated by Django 5.2.14 on 2026-06-08 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0019_relabel_review_status_ai_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatuteCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_slug', models.CharField(db_index=True, help_text="Normalized lowercase statute reference, URL-safe. e.g. 'minn.stat.609.185' or 'minn.stat.ch.169'.", max_length=64)),
                ('reference_display', models.CharField(help_text="Display form as it appears in the opinion (e.g. 'Minn. Stat. § 609.185').", max_length=128)),
                ('chapter', models.CharField(db_index=True, help_text='Chapter number portion of the citation. Always set.', max_length=16)),
                ('section', models.CharField(blank=True, default='', help_text="Section portion (the digits after '.' in 609.185). Blank for chapter-only cites.", max_length=16)),
                ('subdivision', models.CharField(blank=True, default='', help_text='Subdivision (subd. 1, subd. 2a, ...). Blank when absent.', max_length=16)),
                ('text_offset', models.IntegerField(default=0, help_text='Character offset in opinion.raw_text where this citation starts. Used to pull surrounding context for the statute page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statute_citations', to='opinions.opinion')),
            ],
            options={
                'ordering': ['opinion', 'text_offset'],
                'indexes': [models.Index(fields=['reference_slug'], name='opinions_st_referen_ea731f_idx'), models.Index(fields=['chapter', 'section'], name='opinions_st_chapter_b9626f_idx')],
            },
        ),
    ]
