# Generated by Django 5.2.14 on 2026-06-08 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0020_statutecitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='embedded_at',
            field=models.DateTimeField(blank=True, help_text='When this tag was last embedded. Used by embed_tags to skip re-embedding.', null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='embedding',
            field=models.JSONField(blank=True, help_text="voyage-law-2 embedding of (label + description), input_type='document'. 1024 floats, stored as JSON because the Tag table is tiny (~30-200 rows) and indexed similarity search isn't needed -- we cosine-compare in Python against opinion embeddings during suggest_tags. Null until embed_tags has embedded this tag; suggestion logic skips unembedded tags silently.", null=True),
        ),
        migrations.CreateModel(
            name='TagSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(help_text='Cosine similarity 0.0-1.0 between opinion + tag embeddings at scoring time.')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('accepted', 'Accepted (tag applied)'), ('rejected', 'Rejected'), ('auto_applied', 'Auto-applied (high confidence)')], db_index=True, default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, default='', help_text='Username of the editor who accepted/rejected this suggestion.', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_suggestions', to='opinions.opinion')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='opinions.tag')),
            ],
            options={
                'ordering': ['-confidence'],
                'indexes': [models.Index(fields=['status', '-confidence'], name='opinions_ta_status_e4faa2_idx'), models.Index(fields=['tag', 'status'], name='opinions_ta_tag_id_4030dd_idx')],
                'unique_together': {('opinion', 'tag')},
            },
        ),
    ]
