# Generated by Django 5.2.14 on 2026-06-26 01:33

from django.db import migrations, models


def prepare_connection(apps, schema_editor):
    """Make the 7 ALTERs below safe to run against a 2.75 GB table.

    Two guards, both session-scoped so the web tier is unaffected:

    1. ``max_statement_time = 0`` -- settings' init_command pins every
       connection to 25s (right for the web tier, too tight for schema ops).
       Adding ``holding_review_status`` with ``db_index=True`` builds an index
       over opinions_opinion; past the cap it gets KILLed mid-statement
       (errno 1317), leaving the schema half-applied. Pattern from 0023.

    2. ``alter_algorithm = 'NOCOPY'`` -- THE IMPORTANT ONE. opinions_opinion
       is ~2.75 GB (the raw_text / html_content TEXT blobs), and a COPY-
       algorithm ALTER rebuilds the whole table through NFSN's 8 MB InnoDB
       buffer pool. That is not a slow migration, it is an UNKILLABLE one:
       the 2026-06-26 VECTOR INDEX attempt ran 9+ hours, ignored KILL and
       KILL QUERY during the copy stage, and could not be stopped because you
       cannot restart a shared MariaDB daemon. See the "MariaDB VECTOR INDEX
       is infeasible" gotcha in CLAUDE.md.

       NOCOPY forbids the COPY path outright, so if MariaDB cannot do one of
       these as INSTANT/INPLACE it raises errno 1845 IMMEDIATELY instead of
       starting a rebuild we cannot abort. A migration that fails in one
       second is strictly better than one that cannot be stopped -- if it
       does fail, split that column out rather than removing this guard.

    Both are vendor-guarded so local SQLite dev is a clean no-op.
    """
    connection = schema_editor.connection
    if connection.vendor != "mysql":
        return
    with connection.cursor() as cursor:
        cursor.execute("SET SESSION max_statement_time = 0")
        cursor.execute("SET SESSION alter_algorithm = 'NOCOPY'")


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0025_opinioncitation'),
    ]

    operations = [
        migrations.RunPython(
            prepare_connection,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='opinion',
            name='holding_extracted_at',
            field=models.DateTimeField(blank=True, help_text='When holding extraction last ran for this opinion.', null=True),
        ),
        migrations.AddField(
            model_name='opinion',
            name='holding_model',
            field=models.CharField(blank=True, default='', help_text="Provenance of holding_summary -- which extractor produced it (e.g. 'extractive-v1'). Deterministic extraction is the default and quotes the court verbatim; if an LLM is ever run over the residual it records its model id here instead, so the two methods stay auditable side by side on every row.", max_length=64),
        ),
        migrations.AddField(
            model_name='opinion',
            name='holding_review_status',
            field=models.CharField(choices=[('ai_only', 'Processed'), ('flagged', 'Flagged for review'), ('reviewed', 'Human-reviewed')], db_index=True, default='ai_only', help_text='Editorial review state of the holding -- SAME enum + public dot-color semantics as review_status, but tracked independently. Defaults to AI_ONLY on fresh extraction; flip to REVIEWED via the admin holdings-review action once a human has read and (optionally) edited it.', max_length=16),
        ),
        migrations.AddField(
            model_name='opinion',
            name='holding_reviewed_at',
            field=models.DateTimeField(blank=True, help_text='Auto-stamped when holding_review_status flips to human-reviewed.', null=True),
        ),
        migrations.AddField(
            model_name='opinion',
            name='holding_reviewed_by',
            field=models.CharField(blank=True, default='', help_text='Username of the editor who marked this holding human-reviewed.', max_length=120),
        ),
        migrations.AddField(
            model_name='opinion',
            name='holding_source_paras',
            field=models.JSONField(blank=True, default=list, help_text="Court-assigned paragraph numbers (ints) the holding was drawn from, so the UI can deep-link 'From paragraphs ¶12, ¶47' to the cite-anchored #para-N targets. ONLY the court's own [¶N] markers ever appear here -- empty list when the opinion carries none, since a synthesized pinpoint cite would misstate the record."),
        ),
        migrations.AddField(
            model_name='opinion',
            name='holding_summary',
            field=models.TextField(blank=True, default='', help_text="What the court held. Populated by extract_holdings as the court's OWN sentence, quoted verbatim -- not a paraphrase or a generated summary. Empty until extraction runs, and the public section doesn't render when blank (a blank holding is honest; a guessed one would misstate the record)."),
        ),
    ]
