# Generated by Django 5.2.14 on 2026-08-04 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0028_opinioncitation_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParallelCite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cite', models.CharField(db_index=True, help_text="Full citation as '<volume> <reporter> <page>', e.g. '221 Ariz. 236'.", max_length=64)),
                ('reporter', models.CharField(blank=True, default='', help_text="Reporter abbreviation alone, e.g. 'Ariz.', 'P.3d', 'N.W.2d'.", max_length=32)),
                ('opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parallel_cites', to='opinions.opinion')),
            ],
            options={
                'indexes': [models.Index(fields=['cite'], name='parallelcite_cite_idx')],
                'constraints': [models.UniqueConstraint(fields=('opinion', 'cite'), name='uniq_parallel_cite_per_opinion')],
            },
        ),
    ]
