# Generated by Django 5.2.14 on 2026-08-06 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0029_parallelcite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QueryEmbedding',
        ),
    ]
