# Generated by Django 5.2.14 on 2026-08-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0031_opinionembedding_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='cl_absent',
            field=models.BooleanField(default=False, help_text="A human confirmed this is a real judge that CourtListener's people DB does not carry (CL is FJC/federal-heavy and omits many state judges -- e.g. NH's Hantz Marconi). This is a TERMINAL resolution state, equal to having a courtlistener_id: it takes the row out of the 'unresolved / needs a CL lookup' pile without faking an id. Leave False for rows not yet reviewed."),
        ),
    ]
