# Generated by Django 5.2.14 on 2026-08-08 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0033_judge_vice_chief_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='court',
            options={'ordering': ['state__code', 'level', 'division']},
        ),
        migrations.AlterUniqueTogether(
            name='court',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='court',
            name='division',
            field=models.CharField(blank=True, default='', help_text="Division / district designator for multi-panel appellate systems (e.g. '1' and '2' for the Arizona Court of Appeals' two divisions; '1st'-'6th' for California's districts). Empty for single-court levels -- a state Supreme Court, or a unified Court of Appeals like Minnesota's. Part of the court's identity, so (state, level, division) is unique.", max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='court',
            unique_together={('state', 'level', 'division')},
        ),
    ]
