# Generated by Django 5.2.14 on 2026-08-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0034_court_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='role',
            field=models.CharField(blank=True, choices=[('CHIEF_JUSTICE', 'Chief Justice'), ('VICE_CHIEF_JUSTICE', 'Vice Chief Justice'), ('ASSOCIATE_JUSTICE', 'Associate Justice'), ('CHIEF_JUDGE', 'Chief Judge'), ('VICE_CHIEF_JUDGE', 'Vice Chief Judge'), ('JUDGE', 'Judge'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=24),
        ),
    ]
