# Generated by Django 5.2.14 on 2026-08-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0038_panelvote_judge_cascade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SENIOR', 'Senior'), ('RETIRED', 'Retired'), ('DESIGNATED', 'Sitting by designation'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=16),
        ),
    ]
