# Generated by Django 5.2.14 on 2026-08-24 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0039_judge_status_designated'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeSlugAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='The OLD slug that should redirect.', max_length=128)),
                ('note', models.CharField(blank=True, default='', help_text='Why the slug changed (shown only in admin).', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('judge', models.ForeignKey(help_text='The judge this old slug now points to.', on_delete=django.db.models.deletion.CASCADE, related_name='slug_aliases', to='opinions.judge')),
            ],
            options={
                'verbose_name_plural': 'judge slug aliases',
                'indexes': [models.Index(fields=['slug'], name='opinions_ju_slug_d0813a_idx')],
                'unique_together': {('judge', 'slug')},
            },
        ),
    ]
