# Generated by Django 5.2.14 on 2026-08-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0040_judge_slug_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='first_vote_date',
            field=models.DateField(blank=True, help_text='Derived: earliest opinion release_date this judge sat on. Maintained by backfill_judge_spans; do not edit by hand.', null=True),
        ),
        migrations.AddField(
            model_name='judge',
            name='last_vote_date',
            field=models.DateField(blank=True, help_text='Derived: latest opinion release_date this judge sat on. Maintained by backfill_judge_spans; do not edit by hand.', null=True),
        ),
    ]
