# Generated by Django 5.2.14 on 2026-09-18 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0041_judge_vote_span'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_on', models.DateField(help_text='Date the request arrived.')),
                ('status', models.CharField(choices=[('received', 'Received -- not yet answered'), ('declined', 'Declined (per /takedown/ policy)'), ('corrected', 'Declined, but we fixed an error they found'), ('deindexed', 'De-indexed (rare, discretionary)'), ('sealed', 'Removed under a sealing order'), ('withdrawn', 'Withdrawn / no further contact')], db_index=True, default='received', max_length=16)),
                ('requester', models.CharField(blank=True, default='', help_text='Short label only, so a repeat request is recognizable (usually the party named in the opinion). Not a contact record -- do not paste addresses or message text here.', max_length=120)),
                ('notes', models.TextField(blank=True, default='', help_text='Internal reasoning: what was asked, what we did, and whether any factual error was identified and fixed. Never shown publicly.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removal_requests', to='opinions.opinion')),
            ],
            options={
                'verbose_name': 'removal / de-indexing request',
                'verbose_name_plural': 'removal / de-indexing requests',
                'ordering': ['-received_on', '-id'],
                'indexes': [models.Index(fields=['opinion'], name='removalreq_opinion_idx')],
            },
        ),
    ]
