# Generated by Django 5.2.14 on 2026-09-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0042_removal_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='photo_credit',
            field=models.CharField(blank=True, default='', help_text="Public attribution line for the portrait, shown under the photo on the judge's page -- e.g. 'Arizona Court of Appeals, Division One'. Set ONLY when a court supplied the image to us directly. Leave empty for scraped portraits: crediting a court for an image we took off its website would imply cooperation that didn't happen.", max_length=160),
        ),
    ]
